package service

func addAllowedCryptoValues(info map[string]int, values ...string) {
	for i, value := range values {
		info[value] = i
	}
}

func FillAllowedValues(info *map[string]int) {
	// num == 1 equal to Allowed Crypto Name in main.go
	// num == 2 equal to Allowd Crypto Symbol in main.go
	allowedCryptoName := []string{
		"bitcoin",
		"ethereum",
		"tether",
		"binance-coin",
		"usd-coin",
		"xrp",
		"binance-usd",
		"cardano",
		"dogecoin",
		"polygon",
		"solana",
		"polkadot",
		"terra-luna",
		"shiba-inu",
		"litecoin",
		"multi-collateral-dai",
		"tron",
		"avalanche",
		"uniswap",
		"wrapped-bitcoin",
		"unus-sed-leo",
		"chainlink",
		"monero",
		"cosmos",
		"ethereum-classic",
		"bitcoin-cash",
		"stellar",
		"okb",
		"crypto-com-coin",
		"near-protocol",
		"filecoin",
		"quant",
		"lido-dao",
		"algorand",
		"vechain",
		"internet-computer",
		"decentraland",
		"aave",
		"bitcoin-bep2",
		"eos",
		"the-sandbox",
		"flow",
		"trueusd",
		"elrond-egld",
		"tezos",
		"theta",
		"fantom",
		"chiliz",
		"bitcoin-sv",
		"hedera-hashgraph",
		"axie-infinity",
		"huobi-token",
		"kucoin-token",
		"zcash",
		"the-graph",
		"maker",
		"frax-share",
		"curve-dao-token",
		"ftx-token",
		"trust-wallet-token",
		"pancakeswap",
		"klaytn",
		"iota",
		"ecash",
		"thorchain",
		"dash",
		"neo",
		"synthetix-network-token",
		"helium",
		"fei-protocol",
		"mina",
		"nexo",
		"gatetoken",
		"zilliqa",
		"enjin-coin",
		"casper",
		"kava",
		"1inch",
		"convex-finance",
		"compound",
		"loopring",
		"rocket-pool",
		"stacks",
		"basic-attention-token",
		"holo",
		"xinfin-network",
		"gala",
		"nem",
		"decred",
		"celo",
		"balancer",
		"wootrade",
		"kusama",
		"arweave",
		"bitcoin-gold",
		"ravencoin",
		"gnosis-gno",
		"oasis-network",
		"sushiswap",
		"defichain",
	}
	addAllowedCryptoValues(*info, allowedCryptoName...)
}
